### PR TITLE
use version number instead of release in .travis.yml

### PR DESCRIPTION
**Pull request by tkelman**
release will change over time, but your REQUIRE file says this package supports julia 0.4 so it should continue to be tested

### CODE REVIEW

**Comment by loganwilliams** [comment]
I added a version number to match the REQUIRE file in addition to testing against release. 2ef607c3cf6b5892b7b68e506b1a5e22d8ea1b81

**Comment by tkelman** [comment]
You should stop using `release` in travis.

**Comment by loganwilliams** [comment]
Could you elaborate please?

**Comment by tkelman** [comment]
`release` is redundant - it currently means the same thing as `0.6` but is effectively deprecated and not recommended to use going forward

**Comment by loganwilliams** [comment]
[This page](https://docs.travis-ci.com/user/languages/julia/) still suggests that you can "select the most recent release version."

**Comment by tkelman** [comment]
By which it means a version number. The string `release` is no longer documented as an allowable entry, and is only currently kept working for backwards compatibility with people who didn't merge these pull requests removing it.

**Comment by loganwilliams** [comment]
Okay. Saying that is a lot more helpful than saying "You should [x]." with no explanation.

**Pull request closed without merging**
